backend:
  name: github
  branch: dev
  repo: SpiritbloomPro/new-spiritbloom

site_url: https://new.spiritbloom.pro
logo :
  src: https://new.spiritbloom.pro/img/Spiritbloom.png
  show_in_header: true

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          format: webp
          width: 2048
          height: 2048
        svg:
          optimize: true
  stock_assets:
    providers: []

output:
  omit_empty_optional_fields: true

collections:
- name: general
  label: "General Guide"
  folder: general
  media_folder: /static/img/general
  public_folder: /img/general
  icon: star
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: description, label: Description, widget: string}
    - { name: unlisted, label: Unlisted, widget: boolean, required: false }
    - { name: body, label: Content, widget: markdown }
    - { name: sidebar_position, label: Sidebar Position, widget: number, min: 1, max: 20}
- name: preservation
  label: "Preservation Guide"
  folder: preservation
  media_folder: /static/img/evoker
  public_folder: /img/evoker
  icon: nest_eco_leaf
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: description, label: Description, widget: string }
    - { name: unlisted, label: Unlisted, widget: boolean, required: false }
    - { name: body, label: Content, widget: markdown }
    - { name: sidebar_position, label: Sidebar Position, widget: number, min: 1, max: 20 }
- name: holy-paladin
  label: "Holy Paladin Guide"
  folder: holy-paladin
  media_folder: /static/img/paladin
  public_folder: /img/paladin
  icon: brightness_5
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: description, label: Description, widget: string}
    - { name: unlisted, label: Unlisted, widget: boolean, required: false }
    - { name: body, label: Content, widget: markdown }
    - { name: sidebar_position, label: Sidebar Position, widget: number, min: 1, max: 20}
- name: restoration-shaman
  label: "Restoration Shaman Guide"
  folder: restoration-shaman
  media_folder: /static/img/shaman
  public_folder: /img/shaman
  icon: water_drop
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: description, label: Description, widget: string}
    - { name: unlisted, label: Unlisted, widget: boolean, required: false }
    - { name: body, label: Content, widget: markdown }
    - { name: sidebar_position, label: Sidebar Position, widget: number, min: 1, max: 20}
- name: blog
  label: "Blog"
  folder: blog
  media_folder: /static/img/blog
  public_folder: /img/blog
  icon: article
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: date, label: Date, widget: datetime, default: "{{now}}", date_format: "YYYY-MM-DD", time_format: false }
    - { name: description, label: Description, widget: string}
    - { name: unlisted, label: Unlisted, widget: boolean, required: false }
    - { name: body, label: Content, widget: markdown }
    - label: "Tags"
      name: "tags"
      widget: "select"
      multiple: true
      options: ["evoker", "paladin", "shaman", "general"]
    - label: "Authors"
      name: "authors"
      widget: "select"
      multiple: true
      options: ["harrek", "frug", "youtee", "kig"]
- name: config
  label: Configurations
  icon: edit_square
  media_folder: /static/img/config
  public_folder: /img/config
  editor:
    preview: false
  files:
    - name: authors
      label: Authors
      file: blog/authors.yml
      delete: false
      editor:
        preview: false
      fields:
        - name: harrek
          label: Harrek
          widget: object
          collapsed: true
          required: false
          fields:
            - name: name
              label: Name
              widget: string
            - name: title
              label: Title
              widget: string
              required: false
            - name: url
              label: Personal Website
              widget: string
              required: false
            - name: image_url
              label: Image
              widget: image
            - name: description
              label: Description
              widget: text
              required: false
            - name: page
              label: Page
              widget: hidden
              default: true
            - name: socials
              label: Socials
              widget: object
              collapsed: true
              required: false
              fields:
                - name: x
                  label: X/Twitter
                  widget: string
                  required: false
                - name: bluesky
                  label: Bluesky
                  widget: string
                  required: false
                - name: youtube
                  label: Youtube
                  widget: string
                  required: false
                - name: twitch
                  label: Twitch
                  widget: string
                  required: false
                - name: github
                  label: Github
                  widget: string
                  required: false
        - name: frug
          label: Fruggie
          widget: object
          collapsed: true
          required: false
          fields:
            - name: name
              label: Name
              widget: string
            - name: title
              label: Title
              widget: string
              required: false
            - name: url
              label: Personal Website
              widget: string
              required: false
            - name: image_url
              label: Image
              widget: image
            - name: description
              label: Description
              widget: text
              required: false
            - name: page
              label: Page
              widget: hidden
              default: true
            - name: socials
              label: Socials
              widget: object
              collapsed: true
              required: false
              fields:
                - name: x
                  label: X/Twitter
                  widget: string
                  required: false
                - name: bluesky
                  label: Bluesky
                  widget: string
                  required: false
                - name: youtube
                  label: Youtube
                  widget: string
                  required: false
                - name: twitch
                  label: Twitch
                  widget: string
                  required: false
                - name: github
                  label: Github
                  widget: string
                  required: false
        - name: youtee
          label: YouTee
          widget: object
          collapsed: true
          required: false
          fields:
            - name: name
              label: Name
              widget: string
            - name: title
              label: Title
              widget: string
              required: false
            - name: url
              label: Personal Website
              widget: string
              required: false
            - name: image_url
              label: Image
              widget: image
            - name: description
              label: Description
              widget: text
              required: false
            - name: page
              label: Page
              widget: hidden
              default: true
            - name: socials
              label: Socials
              widget: object
              collapsed: true
              required: false
              fields:
                - name: x
                  label: X/Twitter
                  widget: string
                  required: false
                - name: bluesky
                  label: Bluesky
                  widget: string
                  required: false
                - name: youtube
                  label: Youtube
                  widget: string
                  required: false
                - name: twitch
                  label: Twitch
                  widget: string
                  required: false
                - name: github
                  label: Github
                  widget: string
                  required: false
        - name: kig
          label: Kig
          widget: object
          collapsed: true
          required: false
          fields:
            - name: name
              label: Name
              widget: string
            - name: title
              label: Title
              widget: string
              required: false
            - name: url
              label: Personal Website
              widget: string
              required: false
            - name: image_url
              label: Image
              widget: image
            - name: description
              label: Description
              widget: text
              required: false
            - name: page
              label: Page
              widget: hidden
              default: true
            - name: socials
              label: Socials
              widget: object
              collapsed: true
              required: false
              fields:
                - name: x
                  label: X/Twitter
                  widget: string
                  required: false
                - name: bluesky
                  label: Bluesky
                  widget: string
                  required: false
                - name: youtube
                  label: Youtube
                  widget: string
                  required: false
                - name: twitch
                  label: Twitch
                  widget: string
                  required: false
                - name: github
                  label: Github
                  widget: string
                  required: false
    - name: evoker-spells
      label: Evoker Spells
      file: /static/spells/evoker.json
      delete: false
      editor:
        preview: false
      fields:
        - { name: active-spells, label: Active Spells, widget: keyvalue, required: false }
        - { name: class-talents, label: Class Talents, widget: keyvalue, required: false }
        - { name: spec-talents, label: Spec Talents, widget: keyvalue, required: false }
        - { name: hero-talents, label: Hero Talents, widget: keyvalue, required: false }
        - { name: other, label: Others, widget: keyvalue, required: false }
    - name: paladin-spells
      label: Paladin Spells
      file: /static/spells/paladin.json
      delete: false
      editor:
        preview: false
      fields:
        - { name: active-spells, label: Active Spells, widget: keyvalue, required: false }
        - { name: class-talents, label: Class Talents, widget: keyvalue, required: false }
        - { name: spec-talents, label: Spec Talents, widget: keyvalue, required: false }
        - { name: hero-talents, label: Hero Talents, widget: keyvalue, required: false }
        - { name: other, label: Others, widget: keyvalue, required: false }
    - name: shaman-spells
      label: Shaman Spells
      file: /static/spells/shaman.json
      delete: false
      editor:
        preview: false
      fields:
        - { name: active-spells, label: Active Spells, widget: keyvalue, required: false }
        - { name: class-talents, label: Class Talents, widget: keyvalue, required: false }
        - { name: spec-talents, label: Spec Talents, widget: keyvalue, required: false }
        - { name: hero-talents, label: Hero Talents, widget: keyvalue, required: false }
        - { name: other, label: Others, widget: keyvalue, required: false }
    - name: other-spells
      label: Other Spells
      file: /static/spells/other.json
      delete: false
      editor:
        preview: false
      fields:
        - { name: other, label: Others, widget: keyvalue, required: false }